<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Yav.Coordinator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yav.Core\Yav.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Yav.Tests" />
  </ItemGroup>

</Project>
