<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Yav.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yav.Core\Yav.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Yav.Tests" />
  </ItemGroup>

</Project>
